version: '2'
services:
  biokey-backend:
    build: .
    volumes:
      - ./:/usr/src/app
    environment:
      MONGO_URL: 'mongo'
      MONGO_PORT: '27017'
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-mongodb:/data/db

volumes:
  data-mongodb:
    driver: local