version: '2'
services:
  biokey-backend:
    image: 753940217711.dkr.ecr.us-east-1.amazonaws.com/biokey/backend
    environment:
      MONGO_URL: 'mongo'
      MONGO_PORT: '27017'
    ports:
      - "3000:3000"
    links:
      - mongo
    logging:
      driver: awslogs
      options: 
        awslogs-group: biokey
        awslogs-region: us-east-1
        awslogs-stream-prefix: server
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb
    logging:
      driver: awslogs
      options: 
        awslogs-group: biokey
        awslogs-region: us-east-1
        awslogs-stream-prefix: mongo
        awslogs-stream-prefix: storage
volumes:
  mongodata:
  mongoconfig: